{% set name = "sgtlib" %}
{% set version = "3.5.4" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sgtlib-{{ version }}.tar.gz
  sha256: 7f5a16547b601f77ca1bf0e61b6933a3067bf4982ec1ae9456ac55885ffb9bf3

build:
  entry_points:
    - StructuralGT = sgtlib.entrypoints:main_gui
    - StructuralGT-cli = sgtlib.entrypoints:main_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=80.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy ==2.3.2
    - pandas ==2.3.1
    - scipy ==1.16.0
    - gsd ==4.0.0
    - python-igraph ==0.11.9
    - matplotlib-base ==3.10.3
    - networkx ==3.5
    - scikit-image ==0.25.2
    - opencv ==4.12.0
    - pillow ==11.3.0
    - pyside6 ==6.9.1
    - kneed ==0.8.5
    - xlsxwriter ==3.2.5
    - requests ==2.32.4
    - packaging ==25.0
  run_constrained:
    - ovito ==3.13.0

test:
  imports:
    - sgtlib
  commands:
    - pip check
    - StructuralGT-cli --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A software tool for graph theory analysis of microscopy images.
  home: https://github.com/owuordickson/structural-gt
  license: GPL-3.0-only
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - owuordickson
