{% set name = "sgtlib" %}
{% set version = "3.7.4" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sgtlib-{{ version }}.tar.gz
  sha256: 858b33554e925960b0acb87379f8aef68216255b97140f07483891d111d84b65

build:
  entry_points:
    - StructuralGT = sgtlib.entrypoints:main_gui
    - StructuralGT-cli = sgtlib.entrypoints:main_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=80.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy ==2.2.6
    - pandas ==2.3.2
    - scipy ==1.16.2
    - gsd ==4.0.0
    - python-igraph ==0.11.9
    - matplotlib-base ==3.10.6
    - networkx ==3.5
    - scikit-image ==0.25.2
    - opencv ==4.12.0
    - pillow ==11.3.0
    - pyside6 ==6.9.2
    - kneed ==0.8.5
    - xlsxwriter ==3.2.5
    - requests ==2.32.4
    - packaging ==25.0
    - dropbox ==12.0.2
    - cryptography ==46.0.3
    - scikit-learn ==1.7.2
  run_constrained:
    - ovito ==3.14.0

test:
  imports:
    - sgtlib
  commands:
    - pip check
    - StructuralGT-cli --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A software tool for graph theory analysis of microscopy images.
  home: https://github.com/owuordickson/structural-gt
  license: GPL-3.0-only
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - owuordickson
